/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.36
 * Generated at: 2022-01-15 13:49:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.wed;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class phimle_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/views/wed/header.jsp", Long.valueOf(1642253984143L));
    _jspx_dependants.put("/views/wed/footer.jsp", Long.valueOf(1642254163970L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("                ");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<title>Lâu đài coder</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./style.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./media.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../fontawesome-free-5.15.3-web/css/all.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"./media.css\">\r\n");
      out.write("<link href=\"../paginationjs-master/dist/pagination.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.9.0/slick-theme.min.css\" integrity=\"sha512-17EgCFERpgZKcm0j0fEq1YCJuyAWdz9KUtv1EjVuaOz8pDnh/0nZxmU6BBXwaaxqoi9PQXnRWqlcDB027hgv9A==\" crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.9.0/slick.min.css\" integrity=\"sha512-yHknP1/AwR+yx26cB1y0cjvQUMvEa2PFzt1c9LlS4pRQ5NOTZFWbhBig+X9G9eYW/8m0/4OXNx8pxJ6z57x0dw==\" crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"col-xl-12 col-lg-12 col-sm-12 col-12\">\r\n");
      out.write("\t\t\t    <header id=\"header\" class=\"heading\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t        <!-- HEADING -->\r\n");
      out.write("\t\t\t        <div class=\"logo-search row\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t            <div class=\"logo col-xl-3 col-lg-3 col-sm-3\">\r\n");
      out.write("\t\t\t                <img src=\"./images/logo.png\" alt=\"\">\r\n");
      out.write("\t\t\t            </div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t            <div class=\"input-search search-none col-xl-6 col-lg-5 col-sm-5\">\r\n");
      out.write("\t\t\t                <form id=\"input-search\" action=\"\" method=\"GET\" class=\"bg\">\r\n");
      out.write("\t\t\t                    <div class=\"input-search__sub row\">\r\n");
      out.write("\t\t\t                        <input type=\"text\" name=\"search\" class=\"col-xl-10 col-lg-10 col-sm-10\" placeholder=\"search...\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t                        <button class=\"icon-saearch col-xl-2 col-lg-2 col-sm-2\">\r\n");
      out.write("\t\t\t                            <i class=\"fas fa-search\"></i>\r\n");
      out.write("\t\t\t                        </button>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t                    </div>\r\n");
      out.write("\t\t\t                </form>\r\n");
      out.write("\t\t\t            </div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t            <div class=\"z col-sm-4\">\r\n");
      out.write("\t\t\t                <i class=\"fas fa-bars\" id=\"btn_menu\"></i>\r\n");
      out.write("\t\t\t            </div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t            <div class=\"login-register col-xl-3 col-lg-4 col-sm-12 col-12 none\" id=\"login\">\r\n");
      out.write("\t\t\t                <!-- LOGIN RỒI -->\r\n");
      out.write("\t\t\t                <!-- <div class=\"logged\">\r\n");
      out.write("\t\t\t                        <div class=\"logged-name\">\r\n");
      out.write("\t\t\t                            <div class=\"name-sub row\">\r\n");
      out.write("\t\t\t                                <h1>Đức Tuấn</h1>\r\n");
      out.write("\t\t\t                                <i class=\"fas fa-sort-down\"></i>\r\n");
      out.write("\t\t\t                            </div>\r\n");
      out.write("\t\t\t                        \r\n");
      out.write("\t\t\t                            <ul class=\"logger-sub\">\r\n");
      out.write("\t\t\t                                <li><a href=\"#\">Thông tin tài khoản</a></li>\r\n");
      out.write("\t\t\t                                <li><a href=\"#\">Đổi mật khẩu</a></li>\r\n");
      out.write("\t\t\t                                <li><a href=\"#\">Đăng xuất</a></li>\r\n");
      out.write("\t\t\t                            </ul>\r\n");
      out.write("\t\t\t                        </div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t                        <div class=\"avatar\">\r\n");
      out.write("\t\t\t                            <img src=\"./image/anime-ốc sên.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t                        </div>\r\n");
      out.write("\t\t\t                </div> -->\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t                <!-- CHƯA LOGIN -->\r\n");
      out.write("\t\t\t                <div class=\"No-logged-in row\">\r\n");
      out.write("\t\t\t                    <div class=\"login\">\r\n");
      out.write("\t\t\t                        <a href=\"./login.jsp\" class=\"display-flex\">\r\n");
      out.write("\t\t\t                            <h2>Đăng nhập</h2>\r\n");
      out.write("\t\t\t                            <div class=\"iconlogin-register\">\r\n");
      out.write("\t\t\t                                <i class=\"fas fa-sign-in-alt\"></i>\r\n");
      out.write("\t\t\t                            </div>\r\n");
      out.write("\t\t\t                        </a>\r\n");
      out.write("\t\t\t                    </div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t                    <div class=\"register\">\r\n");
      out.write("\t\t\t                        <a href=\"./register.jsp\" class=\"display-flex\">\r\n");
      out.write("\t\t\t                            <h2>Đăng ký</h2>\r\n");
      out.write("\t\t\t                            <div class=\"iconlogin-register\">\r\n");
      out.write("\t\t\t                                <i class=\"fas fa-user-plus\"></i>\r\n");
      out.write("\t\t\t                            </div>\r\n");
      out.write("\t\t\t                        </a>\r\n");
      out.write("\t\t\t                    </div>\r\n");
      out.write("\t\t\t                </div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t            </div>\r\n");
      out.write("\t\t\t        </div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t        <!-- MENU -->\r\n");
      out.write("\t\t\t        <nav class=\"menu none\" id=\"menu\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t            <ul class=\"display-flex\">\r\n");
      out.write("\t\t\t                <li><a href=\"./home.jsp\" class=\"nav-link tc\">Trang chủ</a></li>\r\n");
      out.write("\t\t\t                <li class=\"tl\">\r\n");
      out.write("\t\t\t                    <a href=\"#\" class=\"display-flex nav-link\">\r\n");
      out.write("\t\t\t                        Thể loại\r\n");
      out.write("\t\t\t                        <i class=\"fas fa-chevron-down\"></i>\r\n");
      out.write("\t\t\t                    </a>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t                    <div class=\"tl-sub row\">\r\n");
      out.write("\t\t\t                        <ul class=\"display-grid display-grid___sub\">\r\n");
      out.write("\t\t\t                            <li><a href=\"#\">Tâm lý - tình cảm</a></li>\r\n");
      out.write("\t\t\t                            <li><a href=\"#\">Khoa học - viễn tưởng</a></li>\r\n");
      out.write("\t\t\t                            <li><a href=\"#\">Hài hước</a></li>\r\n");
      out.write("\t\t\t                            <li><a href=\"#\">Gia đình</a></li>\r\n");
      out.write("\t\t\t                            <li><a href=\"#\">Cổ trang</a></li>\r\n");
      out.write("\t\t\t                            <li><a href=\"#\">Võ thuật</a></li>\r\n");
      out.write("\t\t\t                            <li><a href=\"#\">Phim thiếu nhi</a></li>\r\n");
      out.write("\t\t\t                            <li><a href=\"#\">Kinh dị</a></li>\r\n");
      out.write("\t\t\t                        </ul>\r\n");
      out.write("\t\t\t                    </div>\r\n");
      out.write("\t\t\t                </li>\r\n");
      out.write("\t\t\t                <li><a href=\"./phimhot.jsp\" class=\"nav-link ph\">Phim hót</a></li>\r\n");
      out.write("\t\t\t                <li><a href=\"./phimmoi.jsp\" class=\"nav-link pm\">Phim mới</a></li>\r\n");
      out.write("\t\t\t                <li><a href=\"./phimle.jsp\" class=\"nav-link pl\">Phim lẻ</a></li>\r\n");
      out.write("\t\t\t                <li><a href=\"./phimbo.jsp\" class=\"nav-link pb\">Phim bộ</a></li>\r\n");
      out.write("\t\t\t                <li><a href=\"./phimhoathinh.jsp\" class=\"nav-link hh\">Hoạt hình</a></li>\r\n");
      out.write("\t\t\t                <li><a href=\"#\" class=\"nav-link\"></a></li>\r\n");
      out.write("\t\t\t            </ul>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t        </nav>\r\n");
      out.write("\t\t\t    </header>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t        <style type=\"text/css\">\r\n");
      out.write("\t\t\t\t\t\t.pl{\r\n");
      out.write("\t\t\t\t\t\t\tcolor: var(--color-orange);\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t</style>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("                    <!-- SECTION MOVE -->\r\n");
      out.write("                    <section class=\"container p0 top-header\">\r\n");
      out.write("                        <div class=\"container-title\">\r\n");
      out.write("                            <h1>PHIM LẺ:</h1>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </section>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"data-container\"></div>\r\n");
      out.write("                    <div id=\"pagination-demo1\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <script src=\"http://code.jquery.com/jquery-1.8.2.min.js\"></script>\r\n");
      out.write("        <script src=\"../paginationjs-master/src/pagination.js\"></script>\r\n");
      out.write("\r\n");
      out.write("        <script>\r\n");
      out.write("\r\n");
      out.write("            (function (name) {\r\n");
      out.write("                var container = $('#pagination-' + name);\r\n");
      out.write("                var sources = function () {\r\n");
      out.write("                    var result = [];\r\n");
      out.write("\r\n");
      out.write("                    for (var i = 100; i > 0; i--) {\r\n");
      out.write("                        result.push('<div class=\"status\"><h1>Full 20/20 vietsub</h1></div><img src=\"./images/img-avengers.jpg\" alt=\"\"><div class=\"movie-name\"><h2>phim lẻ ' + i + '</h2></div><div class=\"icon-play\"><i class=\"fas fa-play\"></i></div>');\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    return result;\r\n");
      out.write("                }();\r\n");
      out.write("\r\n");
      out.write("                var options = {\r\n");
      out.write("                    dataSource: sources,\r\n");
      out.write("                    pageSize: 20,\r\n");
      out.write("                    callback: function (response, pagination) {\r\n");
      out.write("                        window.console && console.log(response, pagination);\r\n");
      out.write("\r\n");
      out.write("                        var dataHtml = '<div class=\"container-slider display-grid\">';\r\n");
      out.write("\r\n");
      out.write("                        $.each(response, function (index, item) {\r\n");
      out.write("                            dataHtml += '<a href=\"#\" class=\"product\">' + item + '</a>';\r\n");
      out.write("                        });\r\n");
      out.write("\r\n");
      out.write("                        dataHtml += '</div>';\r\n");
      out.write("\r\n");
      out.write("                        container.prev().html(dataHtml);\r\n");
      out.write("                    }\r\n");
      out.write("                };\r\n");
      out.write("\r\n");
      out.write("                //$.pagination(container, options);\r\n");
      out.write("\r\n");
      out.write("                container.addHook('beforeInit', function () {\r\n");
      out.write("                    window.console && console.log('beforeInit...');\r\n");
      out.write("                });\r\n");
      out.write("                container.pagination(options);\r\n");
      out.write("\r\n");
      out.write("                container.addHook('beforePageOnClick', function () {\r\n");
      out.write("                    window.console && console.log('beforePageOnClick...');\r\n");
      out.write("                    //return false\r\n");
      out.write("                });\r\n");
      out.write("            })('demo1');\r\n");
      out.write("        </script>\r\n");
      out.write("\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"col-xl-12 col-lg-12 col-sm-12 col-12 p0\">\r\n");
      out.write("\t\t\t    <!-- FOOTER -->\r\n");
      out.write("\t\t\t    <footer class=\"footer\">\r\n");
      out.write("\t\t\t        <div class=\"footer-top row\">\r\n");
      out.write("\t\t\t            <div class=\"footer-top__left col-xl-8\">\r\n");
      out.write("\t\t\t                <p>\r\n");
      out.write("\t\t\t                    Xem phim hay miễn phí chất lượng cao với phụ đề tiếng việt - thuyết minh - lồng tiếng.\r\n");
      out.write("\t\t\t                    Wedsite có nhiều thể loại phim phong phú, đặc sắc, nhiều bộ phim hay nhất - mới nhất.\r\n");
      out.write("\t\t\t                    <br> <br>\r\n");
      out.write("\t\t\t                    Website với giao diện trực quan, thuận tiện, tốc độ tải nhanh, với độ tin cậy cao hứa\r\n");
      out.write("\t\t\t                    hẹn sẽ đem lại những trải nghiệm tốt nhất cho người dùng.\r\n");
      out.write("\t\t\t                </p>\r\n");
      out.write("\t\t\t            </div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t            <div class=\"footer-top__right col-xl-4\">\r\n");
      out.write("\t\t\t                <div class=\"footer-top__right--left\">\r\n");
      out.write("\t\t\t                    <p>\r\n");
      out.write("\t\t\t                        <a href=\"#\">Quy định</a>\r\n");
      out.write("\t\t\t                        <a href=\"#\">Chính sách riêng tư</a>\r\n");
      out.write("\t\t\t                        <a href=\"#\">Điều khoản chung</a>\r\n");
      out.write("\t\t\t                    </p>\r\n");
      out.write("\t\t\t                </div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t                <div class=\"footer-top__right--right\">\r\n");
      out.write("\t\t\t                    <p>\r\n");
      out.write("\t\t\t                        <a href=\"#\">Giới thiệu</a>\r\n");
      out.write("\t\t\t                        <a href=\"#\">Trang chủ</a>\r\n");
      out.write("\t\t\t                        <a href=\"#\">Facebook</a>\r\n");
      out.write("\t\t\t                    </p>\r\n");
      out.write("\t\t\t                </div>\r\n");
      out.write("\t\t\t            </div>\r\n");
      out.write("\t\t\t        </div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t        <div class=\"footer-down\">\r\n");
      out.write("\t\t\t            <h2>Wedsite được thực hiện bởi nhóm code: LÂU ĐÀI CODER.</h2>\r\n");
      out.write("\t\t\t        </div>\r\n");
      out.write("\t\t\t    </footer>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<script src=\"./main.js\"></script>\r\n");
      out.write("\t<script src=\"./header.js\"></script>\r\n");
      out.write("\t<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("\t<script src=\"https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.9.0/slick.min.js\" integrity=\"sha512-HGOnQO9+SP1V92SrtZfjqxxtLmVzqZpjFFekvzZVWoiASSQgSr4cw9Kqd2+l8Llp4Gm0G8GIFJ4ddwZilcdb8A==\" crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\"></script>\r\n");
      out.write("\t<script src=\"https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.9.0/slick.js\" integrity=\"sha512-eP8DK17a+MOcKHXC5Yrqzd8WI5WKh6F1TIk5QZ/8Lbv+8ssblcz7oGC8ZmQ/ZSAPa7ZmsCU4e/hcovqR8jfJqA==\" crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\"></script>\r\n");
      out.write("\t\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t$('.autoplay').slick({\r\n");
      out.write("\t\t\tslidesToShow : 5,\r\n");
      out.write("\t\t\tslidesToScroll : 1,\r\n");
      out.write("\t\t\tautoplay : true,\r\n");
      out.write("\t\t\tautoplaySpeed : 1000,\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
